from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[1]

BASE_URL = "https://kolesa.kz"
START_URL = f"{BASE_URL}/cars/"
SEARCH_URL = START_URL
SOURCE_NAME = "kolesa.kz"
DEFAULT_ENGINE = "http"

DATA_DIR = PROJECT_ROOT / "data"
EXPORTS_DIR = DATA_DIR / "exports"
LOGS_DIR = PROJECT_ROOT / "logs"
DB_PATH = DATA_DIR / "cars.db"
LOG_FILE = LOGS_DIR / "parser.log"

TOTAL_LIMIT = 50000
MAX_PER_MODEL = 700
MAX_PER_BRAND = 5000
DEFAULT_TEST_LIMIT = 100

HTTP_CONCURRENCY = 3
MIN_DELAY_SECONDS = 1.5
MAX_DELAY_SECONDS = 4.5
REQUEST_TIMEOUT_SECONDS = 20
MAX_RETRIES = 3
ERROR_STOP_THRESHOLD = 20

DEFAULT_HEADLESS = True
DESCRIPTION_WAIT_MS = 5000
PLAYWRIGHT_TIMEOUT_MS = 30000

USER_AGENT = (
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
    "AppleWebKit/537.36 (KHTML, like Gecko) "
    "Chrome/124.0.0.0 Safari/537.36"
)
ACCEPT_LANGUAGE = "ru-RU,ru;q=0.9,en-US;q=0.8,en;q=0.7"
